spring:
  redis:
    host: redis
  application:
    name: cannon
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres
    #url: jdbc:mysql://mysql:3306/cannon?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: true
  profiles:
    active: local
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

permission:
  jwt:
    anonymousUrls: /v1/email-server/*,/v1/email-template/send/*/**,/v1/enum/*,/v1/login,/graphiql,/graphql,/vendor/**,/v1/menu/**,/actuator/**,/v1/user/register,/v1/user/active/*,/v1/attachment/download,/v1/attachment/upload,/files/*,/images/*,/v1/find-pwd-send-log/**/*
aws:
  s3:
    bucket-name: BUCKET
    access-key: ACCESS_KEY
    secret-key: SECRET_KEY
    region-link: LINK
    key: KEY
